import { ZodFirstPartyTypeKind } from 'zod';
import type { ZodTypeAny } from 'zod';

/**
 * Convert the subset of Zod the platform's DTOs use into JSON Schema.
 *
 * Written here rather than pulled in as a dependency because the API contract is
 * a governed artefact: the OpenAPI document an MDA integrates against should be
 * generated by code this repository owns and tests, not by a transitive package.
 * Anything outside the supported subset raises rather than silently emitting an
 * empty schema, so an undocumented field cannot slip into a published contract.
 */
export function zodToJsonSchema(schema: ZodTypeAny): Record<string, unknown> {
  const definition = schema._def as { typeName: ZodFirstPartyTypeKind } & Record<string, unknown>;

  switch (definition.typeName) {
    case ZodFirstPartyTypeKind.ZodString: {
      const output: Record<string, unknown> = { type: 'string' };
      for (const check of (definition.checks ?? []) as { kind: string; value?: number }[]) {
        if (check.kind === 'min') output.minLength = check.value;
        if (check.kind === 'max') output.maxLength = check.value;
        if (check.kind === 'uuid') output.format = 'uuid';
        if (check.kind === 'email') output.format = 'email';
        if (check.kind === 'url') output.format = 'uri';
        if (check.kind === 'datetime') output.format = 'date-time';
        if (check.kind === 'date') output.format = 'date';
      }
      return output;
    }
    case ZodFirstPartyTypeKind.ZodNumber: {
      const output: Record<string, unknown> = { type: 'number' };
      for (const check of (definition.checks ?? []) as { kind: string; value?: number }[]) {
        if (check.kind === 'int') output.type = 'integer';
        if (check.kind === 'min') output.minimum = check.value;
        if (check.kind === 'max') output.maximum = check.value;
      }
      return output;
    }
    case ZodFirstPartyTypeKind.ZodBoolean:
      return { type: 'boolean' };
    case ZodFirstPartyTypeKind.ZodEnum:
      return { type: 'string', enum: definition.values as string[] };
    case ZodFirstPartyTypeKind.ZodNativeEnum:
      return { type: 'string', enum: Object.values(definition.values as Record<string, string>) };
    case ZodFirstPartyTypeKind.ZodLiteral:
      return { const: definition.value };
    case ZodFirstPartyTypeKind.ZodArray:
      return { type: 'array', items: zodToJsonSchema(definition.type as ZodTypeAny) };
    case ZodFirstPartyTypeKind.ZodObject: {
      const shape = (definition.shape as () => Record<string, ZodTypeAny>)();
      const properties: Record<string, unknown> = {};
      const required: string[] = [];
      for (const [key, value] of Object.entries(shape)) {
        properties[key] = zodToJsonSchema(value);
        if (!value.isOptional()) required.push(key);
      }
      return required.length > 0
        ? { type: 'object', properties, required, additionalProperties: false }
        : { type: 'object', properties, additionalProperties: false };
    }
    case ZodFirstPartyTypeKind.ZodOptional:
    case ZodFirstPartyTypeKind.ZodDefault:
      return zodToJsonSchema(definition.innerType as ZodTypeAny);
    case ZodFirstPartyTypeKind.ZodNullable:
      return { ...zodToJsonSchema(definition.innerType as ZodTypeAny), nullable: true };
    case ZodFirstPartyTypeKind.ZodEffects:
      return zodToJsonSchema(definition.schema as ZodTypeAny);
    case ZodFirstPartyTypeKind.ZodUnion:
      return { oneOf: (definition.options as ZodTypeAny[]).map(zodToJsonSchema) };
    case ZodFirstPartyTypeKind.ZodRecord:
      return { type: 'object', additionalProperties: true };
    case ZodFirstPartyTypeKind.ZodAny:
    case ZodFirstPartyTypeKind.ZodUnknown:
      return {};
    default:
      throw new Error(
        `zodToJsonSchema: unsupported schema kind ${String(definition.typeName)}. ` +
          'Extend the converter rather than publishing an incomplete API contract.',
      );
  }
}
